blank_issues_enabled: false
contact_links:
  - name: ⚠️ Anime extension/source issue
    url: https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose
    about: Issues and requests for official extensions and sources should be opened in the aniyomi-extensions repository instead
  - name: 📦 Aniyomi extensions
    url: https://aniyomi.org/extensions/
    about: Anime extensions and sources
  - name: 🧑‍💻 Aniyomi help discord
    url: https://discord.gg/F32UjdJZrR
    about: Common questions are answered here
  - name: 🖥️ Aniyomi website
    url: https://aniyomi.org/
    about: Guides, troubleshooting, and answers to common questions
